author: "Hamdullah Shah <hamdullah.shah@affinitas.de>"
category: "command"
summary: "Fetch a specific messages from archive"
home: "https://github.com/affinitas/ejabberd-contrib/tree/master/"
url: "https://github.com/affinitas/ejabberd-contrib/archive/master.zip"