author: "Igor Dultsev <igor.dultsev@affinitas.de>"
category: "command"
summary: "Accepts waves from wave service and sends them to clients"
home: "https://github.com/affinitas/ejabberd-contrib/tree/beta/"
url: "https://github.com/affinitas/ejabberd-contrib/archive/beta.zip"
